$schema: https://notify.nhs.uk/fhir/schemas/common/2025-11-draft/nhs-notify-document-reference.schema.json
title: NHS Notify DocumentReference Schema
description: A reference to a document for submission to NHS Notify. Provides metadata about the document so that it can be discovered and managed.
type: object

required:
  - resourceType
  - id
  - status
  - docStatus
  - subject
  - content
  - custodian
  - author
  - date
  - description
properties:
  resourceType:
    type: string
    description: The type of the resource (always 'DocumentReference')"
    const: "DocumentReference"
  id:
    type: string
    description: Logical id of this artifact"
    format: uuid
    examples:
      - "82bfb7f3-4889-4e15-b308-bbe4e3cd431f"
  status:
    type: string
    description: "The status of the document reference (current | superseded | entered-in-error)"
    const: "current"
  docStatus:
    type: string
    description: "The workflow/clinical status of the composition (registered | partial | preliminary | final | amended | corrected | appended | cancelled | entered-in-error | deprecated | unknown)"
  type:
    type: object
    description: "Kind of document (LOINC if possible)"
    properties:
      coding:
        type: array
        description: "Code defined by a terminology system"
        items:
          $ref: "#/$defs/snomedCoding"
  subject:
    type: object
    description: "Who/what is the subject of the document"
    required:
      - identifier
    properties:
      identifier:
        type: object
        description: "An identifier for the target resource"
        required:
          - system
          - value
        properties:
          system:
            type: string
            description: "The namespace for the identifier value"
            const: "https://fhir.nhs.uk/Id/nhs-number"
          value:
            type: string
            description: "NHS number - a 10 digit identifier for patients in the NHS"
            pattern: "^[0-9]{10}$"
  author:
    type: array
    description: "Who and/or what authored the document"
    items:
      $ref: "#/$defs/organisation"
  custodian:
    description: "Organization which maintains the document"
    allOf:
      - $ref: "#/$defs/organisation"
      - type: object
        properties:
          identifier:
            value:
              const: "C4L8E"
  date:
    type: string
    description: "When this document reference was created"
    format: date-time
  description:
    type: string
    description: "Human-readable description of the document"
  content:
    type: array
    description: "Document referenced"
    minItems: 1
    maxItems: 1
    items:
      type: object
      required:
        - attachment
      properties:
        attachment:
          type: object
          description: "Where to access the document"
          required:
            - contentType
            - title
            - data
          properties:
            contentType:
              type: string
              description: "Mime type of the content, with charset etc."
              const: "application/pdf"
            title:
              type: string
              description: "Label to display in place of the data"
            data:
              type: string
              description: "Data inline, base64ed - a stream of bytes, base64 encoded (RFC 4648)"

$defs:
  organisation:
    type: object
    required: [identifier, display]
    properties:
      identifier:
        type: object
        description: "Logical reference, when literal reference is not known"
        required:
          - system
          - value
        properties:
          system:
            type: string
            description: "The namespace for the identifier value"
            const: "https://fhir.nhs.uk/Id/ods-organization-code"
          value:
            type: string
            description: "The value that is unique within the system"
            $comment: "ODS organisation code; for example, C4L8E is NHS ENGLAND: NHS NOTIFY"
      display:
        type: string
        description: "Text alternative for the resource"
  snomedCoding:
    type: object
    $comment: "Currently allowed SNOMED CT codes. More codes to be added (TBC)."
    oneOf:
      - properties:
          system:
            const: "http://snomed.info/sct"
          code:
            const: "308540004"
          display:
            const: "Appointment"
        required: [system, code, display]
      - properties:
          system:
            const: "http://snomed.info/sct"
          code:
            const: "823681000000100"
          display:
            const: "Outpatient appointment letter"
        required: [system, code, display]